// Banco de preguntas de Trivia. mulberry32(seed) elige 5 sin repetir cada día
// (ver buildQuestions en shuffle.mjs) y baraja las opciones de cada una.
export const QUESTIONS = [
  { q: `¿Cuál es el río más largo de la Península Ibérica?`, opts: [`Ebro`, `Tajo`, `Duero`, `Guadalquivir`], a: 1 },
  { q: `¿Cuál es la capital de Canadá?`, opts: [`Toronto`, `Montreal`, `Ottawa`, `Vancouver`], a: 2 },
  { q: `¿En qué país está el monte Kilimanjaro?`, opts: [`Kenia`, `Tanzania`, `Etiopía`, `Sudáfrica`], a: 1 },
  { q: `¿Cuál es el desierto cálido más extenso del mundo?`, opts: [`Gobi`, `Kalahari`, `Sáhara`, `Atacama`], a: 2 },
  { q: `¿Qué océano baña las costas de Portugal?`, opts: [`Atlántico`, `Mediterráneo`, `Índico`, `Pacífico`], a: 0 },
  { q: `¿Cuál es el país más grande del mundo por superficie?`, opts: [`China`, `Canadá`, `Estados Unidos`, `Rusia`], a: 3 },
  { q: `¿Qué comunidad autónoma española es la más extensa?`, opts: [`Andalucía`, `Castilla-La Mancha`, `Castilla y León`, `Aragón`], a: 2 },
  { q: `¿Cuál es la capital de Marruecos?`, opts: [`Casablanca`, `Rabat`, `Marrakech`, `Fez`], a: 1 },
  { q: `¿Qué cordillera separa tradicionalmente Europa de Asia?`, opts: [`Los Alpes`, `El Cáucaso`, `Los Urales`, `Los Cárpatos`], a: 2 },
  { q: `¿En qué país nace el río Amazonas?`, opts: [`Brasil`, `Colombia`, `Perú`, `Ecuador`], a: 2 },
  { q: `¿En qué continente está Egipto?`, opts: [`Asia`, `África`, `Europa`, `Oceanía`], a: 1 },
  { q: `¿Qué mar baña la costa de Valencia?`, opts: [`Cantábrico`, `Mediterráneo`, `Atlántico`, `Mar Menor`], a: 1 },
  { q: `¿En qué año llegó Colón a América?`, opts: [`1492`, `1512`, `1482`, `1502`], a: 0 },
  { q: `¿Quién pintó la bóveda de la Capilla Sixtina?`, opts: [`Leonardo da Vinci`, `Rafael`, `Miguel Ángel`, `Botticelli`], a: 2 },
  { q: `¿Qué civilización construyó Machu Picchu?`, opts: [`Maya`, `Azteca`, `Inca`, `Olmeca`], a: 2 },
  { q: `¿En qué año terminó la Segunda Guerra Mundial?`, opts: [`1943`, `1944`, `1945`, `1946`], a: 2 },
  { q: `¿Quién fue el primer ser humano en pisar la Luna?`, opts: [`Buzz Aldrin`, `Neil Armstrong`, `Yuri Gagarin`, `Michael Collins`], a: 1 },
  { q: `¿Qué imperio tuvo su capital en Constantinopla?`, opts: [`Romano de Occidente`, `Otomano y antes Bizantino`, `Persa`, `Cartaginés`], a: 1 },
  { q: `¿En qué año se publicó la primera parte del Quijote?`, opts: [`1555`, `1605`, `1655`, `1705`], a: 1 },
  { q: `¿Qué faraón es famoso por su tumba casi intacta hallada en 1922?`, opts: [`Ramsés II`, `Keops`, `Tutankamón`, `Akenatón`], a: 2 },
  { q: `¿Qué muro cayó en 1989?`, opts: [`El de Adriano`, `El de Berlín`, `La Muralla China`, `El de las Lamentaciones`], a: 1 },
  { q: `¿Qué reina financió el primer viaje de Colón?`, opts: [`Juana la Loca`, `Isabel la Católica`, `María Tudor`, `Isabel II`], a: 1 },
  { q: `¿Qué famoso transatlántico se hundió en 1912?`, opts: [`Lusitania`, `Queen Mary`, `Titanic`, `Britannic`], a: 2 },
  { q: `¿Cuál es el planeta más grande del sistema solar?`, opts: [`Saturno`, `Júpiter`, `Neptuno`, `Urano`], a: 1 },
  { q: `¿Cuál es el principal componente del aire que respiramos?`, opts: [`Oxígeno`, `Dióxido de carbono`, `Nitrógeno`, `Hidrógeno`], a: 2 },
  { q: `¿Cuál es el hueso más largo del cuerpo humano?`, opts: [`Húmero`, `Tibia`, `Fémur`, `Peroné`], a: 2 },
  { q: `¿Cuál es el animal terrestre más rápido?`, opts: [`León`, `Guepardo`, `Antílope`, `Caballo`], a: 1 },
  { q: `¿Cuántos corazones tiene un pulpo?`, opts: [`Uno`, `Dos`, `Tres`, `Cuatro`], a: 2 },
  { q: `¿Qué metal es líquido a temperatura ambiente?`, opts: [`Plomo`, `Mercurio`, `Estaño`, `Aluminio`], a: 1 },
  { q: `¿Qué órgano produce la insulina?`, opts: [`Hígado`, `Riñón`, `Páncreas`, `Bazo`], a: 2 },
  { q: `¿Cuál es el animal más grande que ha existido jamás?`, opts: [`Diplodocus`, `Ballena azul`, `Megalodón`, `Elefante africano`], a: 1 },
  { q: `¿Qué planeta es conocido como el planeta rojo?`, opts: [`Venus`, `Júpiter`, `Marte`, `Mercurio`], a: 2 },
  { q: `¿Cuántos huesos tiene aproximadamente un adulto?`, opts: [`156`, `206`, `256`, `306`], a: 1 },
  { q: `¿Quién formuló la teoría de la relatividad?`, opts: [`Newton`, `Einstein`, `Galileo`, `Hawking`], a: 1 },
  { q: `¿Cuál es el símbolo químico del oro?`, opts: [`Or`, `Go`, `Au`, `Ag`], a: 2 },
  { q: `¿Qué vitamina sintetiza la piel gracias al sol?`, opts: [`Vitamina A`, `Vitamina C`, `Vitamina D`, `Vitamina B12`], a: 2 },
  { q: `¿Quién pintó el Guernica?`, opts: [`Dalí`, `Picasso`, `Miró`, `Goya`], a: 1 },
  { q: `¿Quién escribió "Cien años de soledad"?`, opts: [`Vargas Llosa`, `Borges`, `García Márquez`, `Cortázar`], a: 2 },
  { q: `¿En qué ciudad está el Museo del Prado?`, opts: [`Barcelona`, `Sevilla`, `Madrid`, `Bilbao`], a: 2 },
  { q: `¿Quién pintó "La noche estrellada"?`, opts: [`Monet`, `Van Gogh`, `Cézanne`, `Gauguin`], a: 1 },
  { q: `¿Quién escribió "Romeo y Julieta"?`, opts: [`Shakespeare`, `Molière`, `Cervantes`, `Dante`], a: 0 },
  { q: `¿De qué país era la pintora Frida Kahlo?`, opts: [`Argentina`, `España`, `México`, `Colombia`], a: 2 },
  { q: `¿Quién es el autor de "El Principito"?`, opts: [`Julio Verne`, `Saint-Exupéry`, `Hermann Hesse`, `Oscar Wilde`], a: 1 },
  { q: `¿Qué arquitecto diseñó la Sagrada Familia?`, opts: [`Calatrava`, `Gaudí`, `Moneo`, `Sert`], a: 1 },
  { q: `¿Quién escribió "La Odisea"?`, opts: [`Sófocles`, `Virgilio`, `Homero`, `Platón`], a: 2 },
  { q: `¿Qué grupo británico popularizó la canción "Let It Be"?`, opts: [`The Rolling Stones`, `The Beatles`, `Queen`, `Pink Floyd`], a: 1 },
  { q: `¿Quién compuso "Las cuatro estaciones"?`, opts: [`Bach`, `Mozart`, `Vivaldi`, `Haydn`], a: 2 },
  { q: `¿Qué instrumento tocaba Paco de Lucía?`, opts: [`Piano`, `Guitarra`, `Violín`, `Cajón`], a: 1 },
  { q: `¿Quién dirigió "Tiburón" y "E.T."?`, opts: [`George Lucas`, `Steven Spielberg`, `James Cameron`, `Ridley Scott`], a: 1 },
  { q: `¿De qué país es originario el tango?`, opts: [`Brasil`, `Argentina`, `Cuba`, `México`], a: 1 },
  { q: `¿Cuántas cuerdas tiene una guitarra española clásica?`, opts: [`Cuatro`, `Cinco`, `Seis`, `Siete`], a: 2 },
  { q: `¿Qué compositor siguió componiendo tras quedarse sordo?`, opts: [`Chopin`, `Beethoven`, `Schubert`, `Brahms`], a: 1 },
  { q: `¿En qué saga aparece un protagonista llamado Frodo?`, opts: [`Harry Potter`, `Narnia`, `El Señor de los Anillos`, `Juego de Tronos`], a: 2 },
  { q: `¿Cada cuántos años se celebran los Juegos Olímpicos de verano?`, opts: [`Cada 2`, `Cada 3`, `Cada 4`, `Cada 5`], a: 2 },
  { q: `¿En qué deporte destacó Rafa Nadal?`, opts: [`Golf`, `Tenis`, `Pádel`, `Bádminton`], a: 1 },
  { q: `¿Cuántos jugadores tiene un equipo de fútbol sobre el campo?`, opts: [`9`, `10`, `11`, `12`], a: 2 },
  { q: `¿En qué país se inventó el baloncesto?`, opts: [`Canadá`, `Estados Unidos`, `Inglaterra`, `Francia`], a: 1 },
  { q: `¿Qué torneo de tenis se juega sobre hierba en Londres?`, opts: [`Roland Garros`, `US Open`, `Wimbledon`, `Open de Australia`], a: 2 },
  { q: `¿Cuántos anillos tiene la bandera olímpica?`, opts: [`Tres`, `Cuatro`, `Cinco`, `Seis`], a: 2 },
  { q: `¿Cuál es el ingrediente principal del gazpacho?`, opts: [`Pepino`, `Tomate`, `Pimiento`, `Pan`], a: 1 },
  { q: `¿Qué país es el mayor productor mundial de aceite de oliva?`, opts: [`Italia`, `Grecia`, `España`, `Túnez`], a: 2 },
  { q: `¿De qué cereal se elabora tradicionalmente la cerveza?`, opts: [`Trigo`, `Maíz`, `Cebada`, `Centeno`], a: 2 },
  { q: `¿Cuántos días tiene un año bisiesto?`, opts: [`364`, `365`, `366`, `367`], a: 2 },
  { q: `¿Cuál es el idioma con más hablantes nativos del mundo?`, opts: [`Inglés`, `Español`, `Chino mandarín`, `Hindi`], a: 2 },
  { q: `¿Qué moneda se usa en Japón?`, opts: [`Won`, `Yuan`, `Yen`, `Ringgit`], a: 2 },
  { q: `¿Qué significan las siglas "www" en las direcciones web?`, opts: [`World Wide Web`, `Web World Wide`, `World Web Wide`, `Wide World Web`], a: 0 },
];
